import { report as r } from './content.js?v=20261005-1';

// This outline follows the source Word report, including its subsection order.
export const sections = [
  ['mo-dau', 'Mở đầu'],
  ['doi-ngu', 'A. Nhân sự nhà trường'], ['tong-quan', 'A. Số lớp và học sinh'], ['to-chuc', 'A. Các tổ chức và cha mẹ học sinh'],
  ['ren-luyen', 'B.1. Giáo dục đạo đức'], ['chuyen-mon', 'B.2. Hoạt động chuyên môn'], ['huong-nghiep', 'B.2. Tư vấn tuyển sinh và hướng nghiệp'],
  ['cau-lac-bo', 'B.3. Hoạt động câu lạc bộ'], ['ky-nang', 'B.3. Giáo dục kỹ năng sống'], ['ngoai-khoa', 'B.3. Phong trào và đoàn thể'],
  ['cong-dong', 'B.4. Công tác xã hội và thiện nguyện'], ['hoc-bong', 'B.4. Gương sáng học đường'],
  ['se-chia', 'B.4. Ủng hộ đồng bào bị thiên tai'], ['tri-an', 'B.4. Tri ân mẹ Việt Nam Anh hùng'],
  ['nha-tinh-ban', 'B.4. Nhà tình bạn và hỗ trợ Cầu Kiệu'], ['nong-thon-moi', 'B.4. Chung tay xây dựng nông thôn mới'], ['qua-xuan', 'B.4. Quà Xuân tặng bạn'],
  ['ket-qua', 'Kết quả rèn luyện và học tập'], ['tot-nghiep', 'Tốt nghiệp và đại học'],
  ['toan-may-tinh', 'Thành tích toán trên máy tính cầm tay'], ['thanh-tich', 'Học sinh giỏi Thành phố'], ['khoa-hoc', 'Khoa học kỹ thuật'],
  ['olympic-30-4', 'Olympic 30/4'], ['olympic-thanh-pho', 'Olympic Thành phố'], ['the-thao', 'Thành tích thể dục thể thao'],
  ['clb-noi-bat', 'Thành tích câu lạc bộ'], ['doan-thanh-nien', 'Thành tích Đoàn Thanh niên'], ['thi-dua', 'Thành tích tập thể sư phạm'],
  ['dinh-huong', 'Phần 2. Chủ đề năm học mới'], ['doi-moi', 'I.1. Phương châm và quy mô'], ['de-an', 'I.1. Các chương trình và đề án'],
  ['dinh-huong-phat-trien', 'I.1. Định hướng phát triển'], ['co-so-vat-chat', 'I.1. Cơ sở vật chất'], ['moi-truong-giao-duc', 'I.1. Môi trường và mục tiêu giáo dục'],
  ['muc-tieu-hoc-sinh', 'I.2. Mục tiêu đối với học sinh'], ['muc-tieu-doi-ngu', 'I.3. Mục tiêu đối với đội ngũ'], ['dong-hanh', 'I.4. Phụ huynh học sinh'],
  ['chuyen-doi-so', 'II.1. Chuyển đổi số và AI'], ['danh-gia', 'II.1. Đổi mới kiểm tra đánh giá'],
  ['trai-nghiem', 'II.2. Đổi mới phương pháp và hoạt động giáo dục'], ['chuong-trinh', 'II.2. Ngoại ngữ, tin học và AI'], ['phat-trien', 'II.2. Nghệ thuật và bơi an toàn'],
  ['phat-trien-doi-ngu', 'II.3. Phát triển đội ngũ'], ['nguon-luc', 'II.4. Nguồn lực và tài chính giáo dục'],
  ['chi-tieu-tap-the', 'Chỉ tiêu tập thể trường'], ['chi-tieu-thi-dua', 'Chỉ tiêu cán bộ, giáo viên, nhân viên'], ['chi-tieu', 'Chỉ tiêu học sinh'], ['cam-on', 'Lời cảm ơn']
];
export const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const text = value => escape(value).replace(/\b\d[\d.]* đồng/g, amount => `<span class="money-amount">${amount}</span>`);
export const format = (value, decimals = 0) => new Intl.NumberFormat('vi-VN', { minimumFractionDigits: decimals, maximumFractionDigits: decimals }).format(value);
export const icon = name => `<i data-lucide="${escape(name)}" aria-hidden="true"></i>`;
export const count = item => `<span class="counter" data-value="${item.value}" data-decimals="${item.decimals || 0}">${format(item.value, item.decimals)}</span><span class="suffix">${escape(item.suffix || '')}</span>`;

export function renderReport(photos) {
  const heading = (id, eyebrow, title) => `<div class="section-heading reveal"><p class="eyebrow"><span>${String(sections.findIndex(s => s[0] === id)).padStart(2, '0')}</span>${eyebrow}</p><h2 id="${id}-title">${title}</h2></div>`;
  const section = (id, theme, eyebrow, title, body) => `<section id="${id}" class="section ${theme}" aria-labelledby="${id}-title"><div class="wrap">${heading(id, eyebrow, title)}${body}</div></section>`;
  const image = (photo, alt, priority = false) => `<img src="${photo.src}" alt="${escape(alt)}" width="${photo.width}" height="${photo.height}" ${priority ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
  const reel = (group, caption, className = '') => {
    const items = photos[group] || [];
    return `<figure class="photo-reel reveal ${className}" data-reel><div class="reel-viewport">${items.map((photo, i) => `<div class="reel-frame ${i === 0 ? 'active' : ''}" ${i ? 'aria-hidden="true"' : ''}>${image(photo, caption + ` · Ảnh ${i + 1}`)}</div>`).join('')}<div class="reel-indicators" aria-hidden="true">${items.map((_, i) => `<span class="${i === 0 ? 'active' : ''}"></span>`).join('')}</div></div><figcaption>${caption} <span>Ảnh tư liệu nhà trường</span></figcaption></figure>`;
  };
  const metrics = (items, className = '') => `<div class="metric-grid ${className}" style="--columns:${Math.min(items.length, 3)}">${items.map((item, i) => `<article class="metric reveal" style="--delay:${i * 100}ms">${item.icon ? `<span class="metric-icon">${icon(item.icon)}</span>` : ''}<strong>${count(item)}</strong><h3>${escape(item.label || item.title)}</h3>${item.detail || item.text ? `<p>${text(item.detail || item.text)}</p>` : ''}</article>`).join('')}</div>`;
  const notes = items => `<div class="note-list">${items.map((value, i) => `<p class="reveal" style="--delay:${i * 90}ms">${icon('check')}<span>${text(value)}</span></p>`).join('')}</div>`;
  const features = items => `<div class="feature-list">${items.map(([symbol, title, detail], i) => `<article class="feature-row reveal" style="--delay:${i * 100}ms"><span class="feature-icon">${icon(symbol)}</span><div><h3>${escape(title)}</h3><p>${text(detail)}</p></div></article>`).join('')}</div>`;
  const split = (body, photo) => `<div class="story-layout"><div class="story-text">${body}</div>${photo}</div>`;
  const featured = item => `<div class="featured-metric reveal"><strong>${count(item)}</strong><h3>${escape(item.label || item.title)}</h3>${item.detail || item.text ? `<p>${text(item.detail || item.text)}</p>` : ''}</div>`;
  const program = item => `<article class="program-feature reveal"><span class="feature-icon">${icon(item.icon)}</span><h3>${escape(item.title)}</h3><strong>${escape(item.amount)}</strong><p>${text(item.description)}</p></article>`;
  const academic = index => featured(r.achievements.academic[index]);
  const rendered = new Map();
  const add = (id, theme, eyebrow, title, body) => rendered.set(id, section(id, theme, eyebrow, title, body));

  rendered.set('mo-dau', `<section id="mo-dau" class="hero" aria-labelledby="hero-title"><div class="hero-image">${image(photos.campus[1], 'Mặt tiền Trường THPT Phú Nhuận', true)}</div><div class="hero-shade"></div><div class="hero-content wrap"><p class="eyebrow hero-enter">HỘI NGHỊ CHA MẸ HỌC SINH · <span class="report-year">2026–2027</span></p><h1 id="hero-title" class="hero-enter">TRƯỜNG THPT<br><span>PHÚ NHUẬN</span></h1><p class="hero-subtitle hero-enter">Tổng kết năm học <span class="report-year">${r.pastYear}</span><br>Phương hướng năm học <span class="report-year">${r.nextYear}</span></p></div><span class="hero-credit">Hình ảnh từ tư liệu nhà trường</span></section>`);
  add('doi-ngu', 'white', 'PHẦN 1 · A. ĐẶC ĐIỂM CHÍNH · NHÂN SỰ', 'Đội ngũ <em>nhà trường</em>', split(`${metrics(r.overview.slice(2))}${metrics(r.qualifications)}${notes([r.organization[0][1], r.organization[1][1], 'Giáo viên giàu kinh nghiệm trong giảng dạy và đều đạt chuẩn giáo viên.'])}`, reel('teachers', 'Các tổ chuyên môn')));
  add('tong-quan', 'paper', 'PHẦN 1 · A. ĐẶC ĐIỂM CHÍNH · QUY MÔ', 'Số lớp <em>và học sinh</em>', metrics(r.overview.slice(0, 2), 'overview-grid'));
  add('to-chuc', 'white', 'PHẦN 1 · A. ĐẶC ĐIỂM CHÍNH · TỔ CHỨC', 'Các tổ chức <em>trong nhà trường</em>', `<div class="organization-grid">${r.organization.slice(2).map(([label, detail]) => `<article class="reveal"><h3>${escape(label)}</h3><p>${text(detail)}</p></article>`).join('')}</div>${notes(['Công đoàn viên tích cực, nhiệt tình trong các hoạt động phong trào.', 'Đoàn trường tạo môi trường hoạt động sôi nổi; nhà trường phối hợp chặt chẽ với cha mẹ học sinh.'])}`);
  add('ren-luyen', 'mint', 'PHẦN 1 · B.1. GIÁO DỤC ĐẠO ĐỨC', 'Rèn luyện <em>và nề nếp</em>', split(notes(['Thường xuyên nhắc nhở, kiểm tra tác phong, trang phục và hành xử văn hóa trong các mối quan hệ.', 'Kiểm tra chặt chẽ chuyên cần, ngăn chặn trốn học và các hoạt động không lành mạnh bên ngoài nhà trường.', 'Nêu gương tốt; nghiêm khắc phê bình học sinh vi phạm kỷ luật.', 'Đánh giá thi đua lớp từng tuần; thông tin kịp thời tình hình học tập đến cha mẹ học sinh để phối hợp giáo dục.']), reel('students', 'Thầy cô và học sinh trong các hoạt động của trường')));
  add('chuyen-mon', 'white', 'PHẦN 1 · B.2. HOẠT ĐỘNG CHUYÊN MÔN', 'Hoạt động <em>chuyên môn</em>', split(notes(r.professionalResults), reel('learning', 'Hoạt động dạy và học')));
  add('huong-nghiep', 'mint', 'PHẦN 1 · B.2. HOẠT ĐỘNG CHUYÊN MÔN', 'Tuyển sinh <em>và hướng nghiệp</em>', `${metrics(r.guidance)}${split(notes(['Phối hợp với các trường đại học tổ chức tư vấn trực tiếp tại lớp cho học sinh khối 12.', 'Tổ chức các chuyến tham quan đại học dành cho học sinh cả 3 khối.']), reel('university', 'Tham quan và tìm hiểu các trường đại học'))}`);
  add('cau-lac-bo', 'white', 'PHẦN 1 · B.3. PHONG TRÀO – ĐOÀN THỂ', 'Hoạt động <em>câu lạc bộ</em>', `${notes(['Duy trì và tổ chức hoạt động hiệu quả các câu lạc bộ học thuật và năng khiếu.', 'Nhiều câu lạc bộ đạt thành tích cấp Quận, cấp Thành phố; phục vụ các chương trình ngoại khóa, chuyên đề giàu tính nhân văn và giáo dục.'])}<div class="club-families">${[['clubAcademic', 'Học thuật', 'Phát triển năng lực học sinh'], ['clubArts', 'Năng khiếu', 'Sở thích và đam mê'], ['clubSocial', 'Trải nghiệm', 'Trải nghiệm và công tác xã hội']].map(([group, title, detail]) => `<article class="club-family"><h3 class="reveal">${title}</h3>${reel(group, title, 'poster-reel')}<p class="reveal">${detail}</p></article>`).join('')}</div><p class="footnote reveal">Nhà trường cấp giấy chứng nhận tham gia CLB cho thành viên cuối năm học.</p>`);
  add('ky-nang', 'white', 'PHẦN 1 · B.3. PHONG TRÀO – ĐOÀN THỂ', 'Kỹ năng sống <em>và tâm lý</em>', split(notes(['Mời chuyên gia tổ chức chuyên đề, giáo dục kỹ năng sống và tư vấn tâm lý lứa tuổi cho học sinh toàn trường.', 'Kỹ năng ứng xử trên không gian mạng; phòng chống tội phạm và bạo lực học đường.', 'Tác hại của thuốc lá điện tử; an toàn giao thông; quản lý tài chính cá nhân.']), reel('skills', 'Chuyên đề giáo dục và kỹ năng sống')));
  add('ngoai-khoa', 'mint', 'PHẦN 1 · B.3. PHONG TRÀO – ĐOÀN THỂ', 'Phong trào <em>và đoàn thể</em>', `${notes(['Về nguồn, tìm hiểu truyền thống Đoàn Thanh niên và kết nạp Đoàn viên mới; giáo dục lòng yêu nước, ý thức vượt khó hiếu học.', 'Phong trào Xanh – Sạch – Đẹp, giữ gìn vệ sinh trường lớp.', 'Thi đua học tốt chào mừng các ngày lễ lớn; thực hiện phương châm Dạy thật tốt, học thật giỏi và mô hình trường học An toàn, Hạnh phúc.', 'Phối hợp với Đoàn Thanh niên tổ chức lễ kỷ niệm, khai giảng, sơ kết và tổng kết.'])}${reel('activities', 'Ngoại khóa và hoạt động tập thể', 'wide-reel')}`);
  add('cong-dong', 'coral', 'PHẦN 1 · B.4. KỸ NĂNG SỐNG – SÁNG TẠO – THIỆN NGUYỆN', 'Công tác xã hội <em>và thiện nguyện</em>', split(notes(['Tổ chức thành công đêm văn nghệ Cây mùa xuân 2026 để thực hiện công tác xã hội và góp quỹ Giúp bạn vượt khó – học tốt.', 'Thiện nguyện xuyên suốt năm học, lan tỏa tinh thần nhân văn, tương thân tương ái đến thầy cô, học sinh, phụ huynh và các nhà tài trợ.', 'Tham gia vận động của công đoàn ngành: ủng hộ giáo viên ngoại thành đón Tết, hiến máu nhân đạo.', 'Tham gia hoạt động tại địa phương: quỹ đền ơn đáp nghĩa, đi bộ vì người nghèo.']), reel('spring', 'Cây mùa xuân và công tác xã hội')));
  add('hoc-bong', 'white', 'PHẦN 1 · B.4. THẮP SÁNG ƯỚC MƠ TUỔI TRẺ VIỆT NAM', 'Gương sáng <em>học đường</em>', `${featured(r.charity[2])}${split(notes(['Giao lưu với cựu học sinh, chia sẻ cách vượt qua khó khăn và áp lực trong học tập, cuộc sống.']), reel('scholarship', 'Học bổng Gương sáng học đường'))}`);
  add('se-chia', 'coral', 'PHẦN 1 · B.4. THẮP SÁNG ƯỚC MƠ TUỔI TRẺ VIỆT NAM', 'Ủng hộ đồng bào <em>bị thiên tai</em>', metrics([r.charity[0]], 'money-grid'));
  add('tri-an', 'mint', 'PHẦN 1 · B.4. THẮP SÁNG ƯỚC MƠ TUỔI TRẺ VIỆT NAM', 'Tri ân <em>gia đình chính sách</em>', `${metrics([{ value: 4000000, suffix: ' đồng', label: 'Giá trị quà tặng' }], 'money-grid')}${notes(['Đoàn trường thăm hỏi và tặng quà mẹ Việt Nam Anh hùng Nguyễn Thị Tư và các gia đình chính sách trên địa bàn quận Phú Nhuận.'])}`);
  add('nha-tinh-ban', 'white', 'PHẦN 1 · B.4. THẮP SÁNG ƯỚC MƠ TUỔI TRẺ VIỆT NAM', 'Nhà tình bạn <em>và sẻ chia</em>', `${metrics([r.charity[1]], 'money-grid')}${split(notes(['Đoàn trường phối hợp với Công đoàn hỗ trợ bạn Dư Thị Yến Nhi, lớp 11A7, Trường THPT Trần Văn Quan, xã Long Điền, Thành phố Hồ Chí Minh.', 'Tặng 1.000 tập trắng cho học sinh khó khăn tại phường Cầu Kiệu, Thành phố Hồ Chí Minh.']), reel('charity', 'Công tác thiện nguyện của nhà trường'))}`);
  add('nong-thon-moi', 'mint', 'PHẦN 1 · B.4. THẮP SÁNG ƯỚC MƠ TUỔI TRẺ VIỆT NAM', 'Chung tay <em>xây dựng nông thôn mới</em>', `${metrics([{ value: 1000, suffix: ' quyển', label: 'Tập trắng cho học sinh khó khăn' }, { value: 3, suffix: ' suất', label: 'Học bổng cho thiếu nhi vượt khó', detail: '1.000.000 đồng / suất' }])}${notes(['Tham gia chương trình Chung tay xây dựng nông thôn mới tại xã Bình Mỹ, Thành phố Hồ Chí Minh.'])}`);
  add('qua-xuan', 'coral', 'PHẦN 1 · B.4. THẮP SÁNG ƯỚC MƠ TUỔI TRẺ VIỆT NAM', 'Quà Xuân <em>tặng bạn</em>', featured(r.charity[3]));
  add('ket-qua', 'white', 'PHẦN 1 · TỔNG HỢP KẾT QUẢ · VỀ PHÍA HỌC SINH', 'Kết quả <em>rèn luyện và học tập</em>', `${metrics([r.results[0], r.results[1], r.results[3]])}${notes(['Không có học sinh học lực Chưa đạt.'])}${metrics([r.results[2]])}`);
  add('tot-nghiep', 'forest', 'PHẦN 1 · VỀ PHÍA HỌC SINH · THPT 2026', 'Tốt nghiệp <em>và đại học</em>', `<p class="footnote reveal">Học sinh khối 12 đậu tốt nghiệp THPT 2026.</p><div class="score-comparison reveal"><div><strong>${format(r.graduation.score, 2)}</strong><span>Điểm TB 3 môn cao nhất</span></div><div><strong>${format(r.graduation.previousScore, 2)}</strong><span>Năm 2025</span></div></div><p class="footnote reveal">Điểm 3 môn cao nhất: ${format(r.graduation.highest, 2)} điểm · Thấp nhất: ${format(r.graduation.lowest, 1)} điểm</p><div class="perfect-scores">${r.graduation.perfect.map(([name, value]) => `<article class="reveal"><strong>${value}<span class="suffix">bài</span></strong><p>điểm 10 môn ${name}</p></article>`).join('')}</div>${featured({ value: r.graduation.university, decimals: 2, suffix: '%', label: 'Trúng tuyển đại học', detail: 'Đợt 1 · Thống kê ngày 30/8/2026' })}`);
  add('toan-may-tinh', 'paper award-section', 'PHẦN 1 · KẾT QUẢ DẠY VÀ HỌC', 'Thành tích <em>dự thi</em>', academic(4));
  add('thanh-tich', 'mint award-section', 'PHẦN 1 · KẾT QUẢ DẠY VÀ HỌC', 'Thành tích <em>dự thi</em>', academic(0));
  add('khoa-hoc', 'white award-section', 'PHẦN 1 · KẾT QUẢ DẠY VÀ HỌC', 'Thành tích <em>dự thi</em>', academic(3));
  add('olympic-30-4', 'coral award-section', 'PHẦN 1 · KẾT QUẢ DẠY VÀ HỌC', 'Thành tích <em>dự thi</em>', academic(2));
  add('olympic-thanh-pho', 'paper award-section', 'PHẦN 1 · KẾT QUẢ DẠY VÀ HỌC', 'Thành tích <em>dự thi</em>', academic(1));
  add('the-thao', 'coral', 'PHẦN 1 · THÀNH TÍCH THỂ DỤC THỂ THAO', 'Thành tích <em>thể thao</em>', `${metrics(r.achievements.sport)}${notes(['Cấp Thành phố: Cờ vua, Cờ tướng, Taekwondo, Karatedo, Bơi, Cầu lông, Bóng bàn và Điền kinh.', 'Toàn quốc: Điền kinh đạt 1 huy chương Vàng, 1 huy chương Đồng; Cầu lông đạt 2 huy chương Vàng.'])}`);
  add('clb-noi-bat', 'white', 'PHẦN 1 · THÀNH TÍCH CÂU LẠC BỘ', 'Dấu ấn <em>câu lạc bộ</em>', `${metrics([{ value: r.clubs.count, label: 'CLB · Đội · Nhóm' }, { value: r.clubs.students, suffix: '+', label: 'Học sinh tham gia' }])}${features(r.clubs.items)}${notes(['Các câu lạc bộ làm phong phú hoạt động nhà trường, tạo sân chơi và lựa chọn về năng khiếu, sở thích và đam mê.'])}`);
  add('doan-thanh-nien', 'mint', 'PHẦN 1 · THÀNH TÍCH ĐOÀN THANH NIÊN', 'Ghi nhận <em>Đoàn Thanh niên</em>', notes(r.youthHonors));
  add('thi-dua', 'white', 'PHẦN 1 · VỀ PHÍA TẬP THỂ SƯ PHẠM', 'Thành tích <em>tập thể sư phạm</em>', `${metrics(r.achievements.teachers)}${notes(['Tập thể Lao động Xuất sắc.', 'Giấy khen thành tích tiêu biểu trong thực hiện nhiệm vụ giáo dục phổ thông năm học 2025–2026, theo Quyết định 3812/QĐ-SGDĐT ngày 07/8/2026.', 'Chi bộ hoàn thành tốt nhiệm vụ.', 'Đoàn TNCS hoàn thành xuất sắc nhiệm vụ; Bằng khen Thành Đoàn.'])}`);
  add('dinh-huong', 'forest', 'PHẦN 2 · PHƯƠNG HƯỚNG – NHIỆM VỤ 2026–2027', 'Chủ đề <em>năm học mới</em>', '<div class="motto reveal"><span>Đổi mới tư duy</span><span>Chuyển biến mạnh mẽ</span><span>Kết quả thực chất</span></div>');
  add('doi-moi', 'white', 'PHẦN 2 · I. MỤC TIÊU · 1. NHÀ TRƯỜNG', 'Phương châm <em>và quy mô</em>', `${notes(['Thực hiện nghiêm túc Chương trình GDPT 2018.', 'Học đi đôi với hành; lý luận gắn với thực tiễn.', 'Giáo dục nhà trường gắn kết với giáo dục gia đình và xã hội.'])}${metrics(r.nextOverview)}`);
  add('de-an', 'mint', 'PHẦN 2 · I.1. NHÀ TRƯỜNG · ĐỊNH HƯỚNG PHÁT TRIỂN', 'Các chương trình <em>và đề án</em>', notes(r.projects));
  add('dinh-huong-phat-trien', 'white', 'PHẦN 2 · I.1. NHÀ TRƯỜNG · ĐỊNH HƯỚNG PHÁT TRIỂN', 'Định hướng <em>phát triển</em>', notes(['Vận dụng linh hoạt phương pháp, hình thức dạy học phát triển năng lực; đa dạng hóa giáo dục, chú trọng trải nghiệm, nghiên cứu khoa học và chuyển đổi số.', 'Thực hiện hiệu quả giáo dục hướng nghiệp, phân luồng học sinh sau THPT.', 'Phát triển giáo viên và cán bộ quản lý đáp ứng Chương trình GDPT; nâng cao chuyên môn, nghiệp vụ, bảo đảm đủ giáo viên theo môn học.', 'Đổi mới cơ chế quản lý; quản trị dân chủ, kỷ cương, nề nếp, chất lượng và hiệu quả; tổ chức thi đua, nhân rộng điển hình tiên tiến.', 'Thúc đẩy dạy học trực tuyến, nghiên cứu bài học trên E-Learning LMS, Google Education và phòng học Google; xây dựng kho học liệu dùng chung, ứng dụng CNTT trong mọi hoạt động giáo dục.']));
  add('co-so-vat-chat', 'paper', 'PHẦN 2 · I.1. NHÀ TRƯỜNG · CƠ SỞ VẬT CHẤT', 'Cơ sở vật chất <em>hiện đại</em>', `<div class="infrastructure">${r.infrastructure.map(([value, label]) => `<article class="reveal"><strong>${escape(value)}</strong><h3>${escape(label)}</h3></article>`).join('')}</div>${reel('campus', 'Cơ sở vật chất và khuôn viên nhà trường', 'wide-reel')}${notes(['Phòng học đạt chuẩn, nhà thi đấu và thiết bị dạy học thiết yếu; hạ tầng CNTT, phần mềm, mạng và chương trình kiểm tra đánh giá đồng bộ.', '3 màn hình LED tại sân khấu chính, hội trường và phòng thao giảng.', 'Phòng học Google cá nhân hóa việc học; lắp bảng kéo, hạ độ cao màn hình tivi tại phòng học khối 10.', 'Củng cố, chỉnh trang môi trường sư phạm xanh – sạch – đẹp, thân thiện.'])}`);
  add('moi-truong-giao-duc', 'mint', 'PHẦN 2 · I.1. NHÀ TRƯỜNG · MỤC TIÊU GIÁO DỤC', 'Môi trường <em>học tập hạnh phúc</em>', notes(['Chú trọng nề nếp, kỷ cương, chất lượng và hiệu quả; giáo dục đạo đức, lối sống, kỹ năng sống, ý thức và trách nhiệm công dân với xã hội, cộng đồng.', 'Nâng cao năng lực cán bộ quản lý, giáo viên để đáp ứng đổi mới Chương trình GDPT.', 'Xây dựng tủ sách lớp học, thư viện mở, không gian xanh.', 'Dạy học phát huy tính tích cực, tự học; dạy học để người học được hạnh phúc.', 'Trường khang trang, sạch đẹp; thầy cô là tấm gương đạo đức, mẫu mực; học sinh học để khẳng định mình, làm công dân tốt, thích ứng với thành phố văn minh và hội nhập quốc tế.', 'Tích cực thi đua phát triển trường học số; chuẩn hóa theo mô hình Trường học hạnh phúc, Trường học Xanh.']));
  add('muc-tieu-hoc-sinh', 'white', 'PHẦN 2 · I. MỤC TIÊU · 2. HỌC SINH', 'Học sinh <em>phát triển toàn diện</em>', notes(['Được giảng dạy bằng phương pháp tiên tiến, hiệu quả, hiện đại để phát triển năng lực bản thân toàn diện.', 'Tham gia tất cả hoạt động giáo dục: học văn hóa, trải nghiệm, hướng nghiệp, chuyên đề nghề nghiệp, rèn luyện kỹ năng; sáng tạo qua hoạt động tổ bộ môn, câu lạc bộ và Đoàn Thanh niên.', 'Có thể chơi ít nhất một môn thể thao; có kiến thức cơ bản về âm nhạc, mỹ thuật và kỹ năng thực hành xã hội để thích ứng cuộc sống, gắn với thực tiễn nghề nghiệp.']));
  add('muc-tieu-doi-ngu', 'mint', 'PHẦN 2 · I. MỤC TIÊU · 3. GIÁO VIÊN, NHÂN VIÊN', 'Đội ngũ <em>gương mẫu và tận tâm</em>', notes(['Giỏi chuyên môn, năng động, sáng tạo; áp dụng phương pháp giảng dạy tiên tiến, hiện đại; hiểu biết xã hội sâu rộng, bản lĩnh chính trị vững vàng, phẩm chất tốt, tận tâm, yêu nghề, mến trẻ.', 'Là tấm gương sáng, mẫu mực; ứng xử sư phạm tốt, truyền lửa và lan tỏa năng lượng tích cực.', 'Giúp học sinh phát triển sự đồng cảm, duy trì các mối quan hệ tích cực và có trách nhiệm với bản thân.']));
  add('dong-hanh', 'white', 'PHẦN 2 · I. MỤC TIÊU · 4. PHỤ HUYNH HỌC SINH', 'Phụ huynh <em>đồng hành</em>', notes(['Được tham gia đánh giá chất lượng nhà trường và giáo viên, góp phần nâng cao chất lượng và tinh thần trách nhiệm của giáo viên.', 'Chủ động nắm bắt sâu sát tình hình học tập, rèn luyện của con em thông qua hệ thống quản lý thông tin, điều hành.', 'Xây dựng liên kết chặt chẽ với nhà trường và giáo viên trong giáo dục học sinh; đóng góp ý kiến kịp thời, hợp lý.']));
  add('chuyen-doi-so', 'paper', 'PHẦN 2 · II.1. ĐỔI MỚI QUẢN LÝ, GIẢNG DẠY VÀ ĐÁNH GIÁ', 'Chuyển đổi số <em>và AI</em>', split(features(r.solutions.slice(0, 2)), reel('digital', 'Học tập trên nền tảng số')));
  add('danh-gia', 'white', 'PHẦN 2 · II.1. ĐỔI MỚI QUẢN LÝ, GIẢNG DẠY VÀ ĐÁNH GIÁ', 'Đổi mới <em>kiểm tra đánh giá</em>', features([r.solutions[2]]));
  add('trai-nghiem', 'mint', 'PHẦN 2 · II.2. ĐỔI MỚI PHƯƠNG PHÁP, HOẠT ĐỘNG GIÁO DỤC', 'Trải nghiệm <em>và hướng nghiệp</em>', split(notes(['Giáo dục STEM/STEAM và nghiên cứu khoa học thực chất, gắn thực tiễn, tránh hình thức phong trào.', 'Mở rộng không gian học tập: thư viện, phòng thí nghiệm, ngoài lớp học và ngoài nhà trường; mỗi tổ bộ môn xây dựng ít nhất 1 tiết trải nghiệm/khối/năm.', 'Hướng nghiệp và khởi nghiệp chuyên sâu gắn với thực tiễn; tư vấn phân luồng học sinh từ khối 10 đến khối 12.']), reel('experience', 'Học bằng trải nghiệm và thực hành')));
  add('chuong-trinh', 'white', 'PHẦN 2 · II.2. XÂY DỰNG CHƯƠNG TRÌNH NHÀ TRƯỜNG', 'Ngoại ngữ, <em>tin học và AI</em>', `<div class="program-grid">${r.programs.slice(0, 3).map(program).join('')}</div>${notes(['Bổ trợ năng lực, phát triển kỹ năng toàn diện cho học sinh; từng bước đưa Tiếng Anh trở thành ngôn ngữ thứ hai.'])}${reel('english', 'Học tập, thực hành và phát triển năng lực', 'wide-reel')}`);
  add('phat-trien', 'mint', 'PHẦN 2 · II.2. XÂY DỰNG CHƯƠNG TRÌNH NHÀ TRƯỜNG', 'Nghệ thuật <em>và bơi an toàn</em>', `<div class="program-grid two-columns">${r.programs.slice(3).map(program).join('')}</div>`);
  add('phat-trien-doi-ngu', 'white', 'PHẦN 2 · II.3. PHÁT TRIỂN NHÀ GIÁO VÀ CÁN BỘ QUẢN LÝ', 'Phát triển <em>đội ngũ</em>', notes(['Thường xuyên rà soát, sắp xếp lại đội ngũ giáo viên.', 'Nâng cao năng lực sử dụng Tin học, Ngoại ngữ cho giáo viên, nhân viên theo kế hoạch.', 'Bồi dưỡng năng lực nghiên cứu khoa học và hướng dẫn học sinh nghiên cứu khoa học; nâng cao năng lực chủ nhiệm, phụ trách Đoàn, CLB và tư vấn học đường.', 'Đánh giá, xếp loại giáo viên và cán bộ quản lý theo chuẩn của Bộ Giáo dục và Đào tạo.']));
  add('nguon-luc', 'paper', 'PHẦN 2 · II.4. NGUỒN LỰC VÀ CƠ CHẾ TÀI CHÍNH GIÁO DỤC', 'Nguồn lực <em>phát triển giáo dục</em>', notes(['Tiếp tục thực hiện xã hội hóa trong giáo dục và đào tạo.', 'Huy động mọi nguồn lực đầu tư để phát triển giáo dục.']));
  add('chi-tieu-tap-the', 'mint', 'PHẦN 2 · CÁC CHỈ TIÊU PHẤN ĐẤU · TẬP THỂ TRƯỜNG', 'Chỉ tiêu <em>tập thể trường</em>', notes([r.targetMore[2][1]]));
  add('chi-tieu-thi-dua', 'white', 'PHẦN 2 · CÁC CHỈ TIÊU · CÁN BỘ, GIÁO VIÊN, NHÂN VIÊN', 'Chỉ tiêu <em>đội ngũ</em>', metrics(r.teacherTargets));
  add('chi-tieu', 'forest', 'PHẦN 2 · CÁC CHỈ TIÊU PHẤN ĐẤU · HỌC SINH', 'Chỉ tiêu <em>học sinh</em>', `${metrics(r.targets.slice(0, 3))}${notes([r.targetMore[0][1]])}${metrics(r.targets.slice(3))}`);
  rendered.set('cam-on', `<section id="cam-on" class="closing-section" aria-labelledby="cam-on-title"><div class="closing-image">${image(photos.school[0], 'Cộng đồng học sinh THPT Phú Nhuận')}</div><div class="closing-shade"></div><div class="wrap closing-content"><p class="eyebrow reveal">TRƯỜNG THPT PHÚ NHUẬN</p><h2 id="cam-on-title" class="reveal">Xin cảm ơn<br><em>sự tin tưởng và đồng hành</em><br>của quý phụ huynh.</h2><p class="reveal">Tổng kết năm học ${r.pastYear}<br>Phương hướng, nhiệm vụ năm học ${r.nextYear}</p></div></section>`);
  return sections.map(([id]) => {
    if (!rendered.has(id)) throw new Error('Missing report section: ' + id);
    return rendered.get(id);
  }).join('\n');
}
