import { report as r } from './content.js?v=20261003-2';

export const sections = [
  ['mo-dau', 'Mở đầu'], ['tong-quan', 'Quy mô nhà trường'], ['doi-ngu', 'Đội ngũ & tổ chức'],
  ['ren-luyen', 'Rèn luyện & nề nếp'], ['ket-qua', 'Kết quả học tập'], ['tot-nghiep', 'Tốt nghiệp & đại học'],
  ['thanh-tich', 'Học sinh giỏi & Olympic'], ['khoa-hoc', 'Khoa học & sáng tạo'], ['the-thao', 'Thành tích thể thao'],
  ['thi-dua', 'Thi đua & ghi nhận'], ['cau-lac-bo', 'Câu lạc bộ học sinh'], ['clb-noi-bat', 'Dấu ấn câu lạc bộ'],
  ['ky-nang', 'Kỹ năng sống'], ['huong-nghiep', 'Tư vấn & hướng nghiệp'], ['ngoai-khoa', 'Hoạt động ngoại khóa'],
  ['se-chia', 'Thiện nguyện'], ['hoc-bong', 'Học bổng & quà Xuân'], ['cong-dong', 'Chung tay cộng đồng'],
  ['dinh-huong', 'Năm học mới'], ['doi-moi', 'Định hướng giáo dục'], ['chuyen-doi-so', 'Chuyển đổi số & AI'],
  ['danh-gia', 'Dạy học & đánh giá'], ['chuong-trinh', 'Ngoại ngữ & công nghệ'], ['phat-trien', 'Nghệ thuật & thể chất'],
  ['co-so-vat-chat', 'Cơ sở vật chất'], ['phat-trien-doi-ngu', 'Phát triển đội ngũ'], ['chi-tieu', 'Chỉ tiêu học sinh'],
  ['chi-tieu-thi-dua', 'Chỉ tiêu thi đua'], ['dong-hanh', 'Gia đình & nhà trường'], ['cam-on', 'Lời cảm ơn']
];
export const chapters = [
  ['mo-dau', 'Nhà trường', 0], ['ren-luyen', 'Kết quả giáo dục', 3], ['thanh-tich', 'Thành tích', 6],
  ['cau-lac-bo', 'Trải nghiệm', 10], ['se-chia', 'Sẻ chia', 15], ['dinh-huong', 'Năm học mới', 18], ['chi-tieu', 'Mục tiêu & đồng hành', 26]
];
export const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export const format = (value, decimals = 0) => new Intl.NumberFormat('vi-VN', { minimumFractionDigits: decimals, maximumFractionDigits: decimals }).format(value);
export const icon = name => `<i data-lucide="${escape(name)}" aria-hidden="true"></i>`;
export const count = item => `<span class="counter" data-value="${item.value}" data-decimals="${item.decimals || 0}">${format(item.value, item.decimals)}</span><span class="suffix">${escape(item.suffix || '')}</span>`;

export function renderReport(photos) {
  const heading = (id, eyebrow, title) => `<div class="section-heading reveal"><p class="eyebrow"><span>${String(sections.findIndex(s => s[0] === id)).padStart(2, '0')}</span>${eyebrow}</p><h2 id="${id}-title">${title}</h2></div>`;
  const section = (id, theme, eyebrow, title, body) => `<section id="${id}" class="section ${theme}" aria-labelledby="${id}-title"><div class="wrap">${heading(id, eyebrow, title)}${body}</div></section>`;
  const image = (photo, alt, priority = false) => `<img src="${photo.src}" alt="${escape(alt)}" width="${photo.width}" height="${photo.height}" ${priority ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
  const reel = (group, caption, className = '') => {
    const items = photos[group] || [];
    return `<figure class="photo-reel reveal ${className}" data-reel><div class="reel-viewport">${items.map((photo, i) => `<div class="reel-frame ${i === 0 ? 'active' : ''}" ${i ? 'aria-hidden="true"' : ''}>${image(photo, caption + ` · Ảnh ${i + 1}`)}</div>`).join('')}<div class="reel-indicators" aria-hidden="true">${items.map((_, i) => `<span class="${i === 0 ? 'active' : ''}"></span>`).join('')}</div></div><figcaption>${caption} <span>Ảnh tư liệu nhà trường</span></figcaption></figure>`;
  };
  const wall = (group, caption, amount = 3) => `<div class="photo-wall">${(photos[group] || []).slice(0, amount).map((photo, i) => `<figure class="reveal" style="--delay:${i * 100}ms">${image(photo, caption + ` · Ảnh ${i + 1}`)}</figure>`).join('')}</div>`;
  const metrics = (items, className = '') => `<div class="metric-grid ${className}" style="--columns:${Math.min(items.length, 3)}">${items.map((item, i) => `<article class="metric reveal" style="--delay:${i * 100}ms">${item.icon ? `<span class="metric-icon">${icon(item.icon)}</span>` : ''}<strong>${count(item)}</strong><h3>${escape(item.label || item.title)}</h3>${item.detail || item.text ? `<p>${escape(item.detail || item.text)}</p>` : ''}</article>`).join('')}</div>`;
  const notes = items => `<div class="note-list">${items.map((text, i) => `<p class="reveal" style="--delay:${i * 90}ms">${icon('check')}<span>${escape(text)}</span></p>`).join('')}</div>`;
  const features = items => `<div class="feature-list">${items.map(([symbol, title, text], i) => `<article class="feature-row reveal" style="--delay:${i * 100}ms"><span class="feature-icon">${icon(symbol)}</span><div><h3>${escape(title)}</h3><p>${escape(text)}</p></div></article>`).join('')}</div>`;
  const split = (text, photo) => `<div class="story-layout"><div class="story-text">${text}</div>${photo}</div>`;
  const featured = item => `<div class="featured-metric reveal"><strong>${count(item)}</strong><h3>${escape(item.label)}</h3>${item.detail ? `<p>${escape(item.detail)}</p>` : ''}</div>`;
  const program = item => `<article class="program-feature reveal"><span class="feature-icon">${icon(item.icon)}</span><h3>${item.title}</h3><strong>${item.amount}</strong><p>${item.description}</p></article>`;

  return `
  <section id="mo-dau" class="hero" aria-labelledby="hero-title">
    <div class="hero-image">${image(photos.campus[1], 'Mặt tiền Trường THPT Phú Nhuận', true)}</div><div class="hero-shade"></div>
    <div class="hero-content wrap"><p class="eyebrow hero-enter">HỘI NGHỊ CHA MẸ HỌC SINH · <span class="report-year">2026–2027</span></p><h1 id="hero-title" class="hero-enter">TRƯỜNG THPT<br><span>PHÚ NHUẬN</span></h1><p class="hero-subtitle hero-enter">Tổng kết năm học <span class="report-year">${r.pastYear}</span><br>Phương hướng năm học <span class="report-year">${r.nextYear}</span></p><a class="hero-link hero-enter" href="#tong-quan">Cùng nhìn lại, cùng bước tiếp ${icon('arrow-down')}</a></div><span class="hero-credit">Hình ảnh từ tư liệu nhà trường</span>
  </section>
  ${section('tong-quan', 'paper', 'TỔNG QUAN · 2025–2026', 'Quy mô <em>nhà trường</em>', `${metrics(r.overview, 'overview-grid')}${reel('school', 'Cộng đồng THPT Phú Nhuận', 'wide-reel')}`)}
  ${section('doi-ngu', 'white', 'CON NGƯỜI & TỔ CHỨC', 'Đội ngũ <em>tận tâm</em>', `${split(`${metrics(r.qualifications)}${notes(['Giáo viên giàu kinh nghiệm, đạt chuẩn chuyên môn.', r.organization[0][1], r.organization[1][1]])}`, reel('teachers', 'Các tổ chuyên môn'))}<div class="organization-grid">${r.organization.slice(2).map(([label, text]) => `<article class="reveal"><h3>${label}</h3><p>${text}</p></article>`).join('')}</div>`)}
  ${section('ren-luyen', 'mint', 'GIÁO DỤC ĐẠO ĐỨC', 'Rèn luyện tốt.<br><em>Nề nếp vững vàng.</em>', split(`${featured(r.results[0])}${notes(['Theo dõi tác phong, chuyên cần và văn hóa ứng xử.', 'Đánh giá thi đua lớp hằng tuần.', 'Phối hợp kịp thời với cha mẹ học sinh.'])}`, reel('students', 'Thầy cô và học sinh trong các hoạt động của trường')))}
  ${section('ket-qua', 'white', 'KẾT QUẢ HỌC TẬP', 'Ghi nhận <em>sự tiến bộ</em>', `${metrics([r.results[1], r.results[3], r.results[2]])}${notes(['Không có học sinh học lực Chưa đạt.'])}${reel('learning', 'Học tập chủ động, hợp tác và thực hành', 'wide-reel')}`)}
  ${section('tot-nghiep', 'forest', 'TỐT NGHIỆP THPT 2026', 'Bước tiếp <em>vào đại học</em>', `${split(`${featured({ value: r.graduation.university, decimals: 2, suffix: '%', label: 'Trúng tuyển đại học', detail: 'Đợt 1 · Thống kê ngày 30/8/2026' })}<div class="score-comparison reveal"><div><strong>${format(r.graduation.score, 2)}</strong><span>Điểm TB 3 môn cao nhất</span></div><div><strong>${format(r.graduation.previousScore, 2)}</strong><span>Năm 2025</span></div></div>`, reel('university', 'Học sinh tìm hiểu môi trường đại học'))}<div class="perfect-scores">${r.graduation.perfect.map(([name, value]) => `<article class="reveal"><strong>${value}</strong><p>điểm 10 môn ${name}</p></article>`).join('')}</div><p class="footnote reveal">Điểm 3 môn cao nhất: ${format(r.graduation.highest, 2)} · Thấp nhất: ${format(r.graduation.lowest, 1)}</p>`)}
  ${section('thanh-tich', 'paper', 'THÀNH TÍCH HỌC THUẬT', 'Học sinh giỏi<br><em>& Olympic</em>', `${metrics(r.achievements.academic.slice(0, 3))}${reel('academic', 'Ghi nhận nỗ lực học tập của học sinh', 'wide-reel')}`)}
  ${section('khoa-hoc', 'white', 'NGHIÊN CỨU & SÁNG TẠO', 'Từ ý tưởng<br><em>đến thực hành</em>', split(`${metrics(r.achievements.academic.slice(3))}${notes(['Phát triển năng lực nghiên cứu khoa học.', 'Học theo dự án, STEM và tích hợp liên môn.'])}`, reel('science', 'Hoạt động khoa học, công nghệ và nghiên cứu')))}
  ${section('the-thao', 'coral', 'THÀNH TÍCH THỂ THAO', 'Bền bỉ rèn luyện.<br><em>Tự tin thi đấu.</em>', `${metrics(r.achievements.sport)}${split(notes(['Thành tích ở Cờ vua, Cờ tướng, Taekwondo, Karatedo, Bơi, Cầu lông, Bóng bàn và Điền kinh.', 'Giải toàn quốc: Điền kinh và Cầu lông.']), reel('sport', 'Hoạt động thể dục thể thao của trường'))}`)}
  ${section('thi-dua', 'mint', 'THI ĐUA & KHEN THƯỞNG', 'Ghi nhận <em>tập thể sư phạm</em>', `${metrics(r.achievements.teachers)}${notes([r.honors, 'Đoàn trường được khen thưởng trong công tác Đoàn, Tháng Thanh niên, Xuân tình nguyện, tình nguyện hè và học tập, làm theo tư tưởng, đạo đức, phong cách Hồ Chí Minh.'])}${wall('teachers', 'Tập thể sư phạm THPT Phú Nhuận')}`)}
  ${section('cau-lac-bo', 'white', 'CÂU LẠC BỘ · ĐỘI · NHÓM', 'Không gian <em>cho đam mê</em>', `${metrics([{ value: r.clubs.count, label: 'CLB · Đội · Nhóm' }, { value: r.clubs.students, suffix: '+', label: 'Học sinh tham gia' }])}<div class="club-families">${[['clubAcademic', 'Học thuật', 'Khoa học, Tin học, Vật lý, Hóa học, Tiếng Anh'], ['clubArts', 'Năng khiếu', 'Âm nhạc, Nhảy, Kịch, Vẽ, Nhiếp ảnh'], ['clubSocial', 'Trải nghiệm', 'Công tác xã hội, Tâm lý, Truyền thông, Bút chì']].map(([group, title, text]) => `<article class="club-family"><h3 class="reveal">${title}</h3>${reel(group, title, 'poster-reel')}<p class="reveal">${text}</p></article>`).join('')}</div><p class="footnote reveal">Nhà trường cấp giấy chứng nhận tham gia CLB cho thành viên cuối năm học.</p>`)}
  ${section('clb-noi-bat', 'paper', 'DẤU ẤN CÂU LẠC BỘ', 'Thỏa sức <em>thể hiện bản thân</em>', `${features(r.clubs.items)}${wall('clubs', 'Hoạt động câu lạc bộ', 4)}`)}
  ${section('ky-nang', 'white', 'KỸ NĂNG SỐNG & TÂM LÝ', 'Hiểu mình.<br><em>Ứng xử có trách nhiệm.</em>', split(`${features([r.education[2]])}${notes(['Phòng chống bạo lực học đường và tội phạm.', 'Hiểu tác hại của thuốc lá điện tử.', 'An toàn giao thông và quản lý tài chính cá nhân.'])}`, reel('skills', 'Chuyên đề giáo dục và kỹ năng sống')))}
  ${section('huong-nghiep', 'mint', 'TUYỂN SINH & HƯỚNG NGHIỆP', 'Tìm hiểu hôm nay.<br><em>Lựa chọn ngày mai.</em>', `${metrics(r.guidance)}${split(notes(['Tư vấn trực tiếp tại lớp cho học sinh khối 12.', 'Tham quan đại học dành cho cả 3 khối.', 'Kết nối sở thích, năng lực và định hướng nghề nghiệp.']), reel('university', 'Tham quan và tìm hiểu các trường đại học'))}`)}
  ${section('ngoai-khoa', 'white', 'TRẢI NGHIỆM & PHONG TRÀO', 'Mỗi hoạt động,<br><em>một bài học mới</em>', `${features([r.education[3]])}${reel('activities', 'Ngoại khóa, văn hóa và hoạt động tập thể', 'wide-reel')}${notes(['Về nguồn, tìm hiểu truyền thống và kết nạp Đoàn viên.', 'Phát triển trường học an toàn, hạnh phúc; xanh – sạch – đẹp.'])}`)}
  ${section('se-chia', 'coral', 'THIỆN NGUYỆN & CÔNG TÁC XÃ HỘI', 'Chung tay <em>sẻ chia</em>', `${metrics(r.charity.slice(0, 2), 'money-grid')}${split(notes(['Ủng hộ đồng bào bị thiên tai qua 2 đợt quyên góp.', 'Công trình Nhà tình bạn hỗ trợ học sinh Trường THPT Trần Văn Quan.']), reel('charity', 'Hoạt động thiện nguyện của nhà trường'))}`)}
  ${section('hoc-bong', 'white', 'ĐỒNG HÀNH CÙNG HỌC SINH', 'Tiếp sức <em>đến trường</em>', `${metrics(r.charity.slice(2))}${reel('scholarship', 'Học bổng và quà tặng dành cho học sinh', 'wide-reel')}${notes(['Giao lưu với cựu học sinh trong chương trình Gương sáng học đường.', 'Chia sẻ cách vượt qua khó khăn và áp lực trong học tập, cuộc sống.'])}`)}
  ${section('cong-dong', 'mint', 'TRÁCH NHIỆM VỚI CỘNG ĐỒNG', 'Lan tỏa <em>tinh thần nhân văn</em>', `${split(notes(r.charityMore), reel('spring', 'Thầy cô, học sinh và phụ huynh cùng làm việc tốt'))}${wall('spring', 'Hoạt động Cây mùa xuân và công tác xã hội')}`)}
  ${section('dinh-huong', 'forest', 'PHƯƠNG HƯỚNG 2026–2027', 'Một năm học mới.<br><em>Một hành trình mới.</em>', `<div class="motto reveal"><span>Đổi mới tư duy</span><span>Chuyển biến mạnh mẽ</span><span>Kết quả thực chất</span></div>${metrics(r.nextOverview)}${reel('campus', 'Không gian học tập tại THPT Phú Nhuận', 'wide-reel')}`)}
  ${section('doi-moi', 'white', 'MỤC TIÊU GIÁO DỤC', 'Học để phát triển.<br><em>Học để trưởng thành.</em>', `<div class="direction-list">${r.directions.map(([number, title, text]) => `<article class="reveal"><span>${number}</span><div><h3>${title}</h3><p>${text}</p></div></article>`).join('')}</div>${notes(['Thực hiện nghiêm túc Chương trình GDPT 2018.', 'Học đi đôi với hành; lý luận gắn với thực tiễn.', 'Gắn kết giáo dục nhà trường, gia đình và xã hội.'])}`)}
  ${section('chuyen-doi-so', 'paper', 'CHUYỂN ĐỔI SỐ & NĂNG LỰC SỐ', 'Công nghệ phục vụ<br><em>việc học</em>', `${split(features(r.solutions.slice(0, 2)), reel('digital', 'Học tập trên nền tảng số'))}${wall('ai', 'Trí tuệ nhân tạo và hoạt động công nghệ')}`)}
  ${section('danh-gia', 'white', 'DẠY HỌC & KIỂM TRA ĐÁNH GIÁ', 'Vì <em>sự tiến bộ</em><br>của học sinh', split(features(r.solutions.slice(2)), reel('experience', 'Học bằng trải nghiệm và thực hành')))}
  ${section('chuong-trinh', 'mint', 'CHƯƠNG TRÌNH NHÀ TRƯỜNG', 'Ngoại ngữ.<br><em>Tin học. Trí tuệ nhân tạo.</em>', `<div class="program-grid">${r.programs.slice(0, 3).map(program).join('')}</div>${reel('english', 'Học tập, thực hành và phát triển năng lực', 'wide-reel')}`)}
  ${section('phat-trien', 'white', 'GIÁO DỤC TOÀN DIỆN', 'Nghệ thuật<br><em>& thể chất</em>', `<div class="program-grid two-columns">${r.programs.slice(3).map(program).join('')}</div>${split(notes(['Học sinh có thể chơi ít nhất một môn thể thao.', 'Có kiến thức cơ bản về âm nhạc, mỹ thuật.', 'Phát triển kỹ năng thực hành xã hội, thích ứng cuộc sống.']), reel('activities', 'Sáng tạo, vận động và hoạt động tập thể'))}`)}
  ${section('co-so-vat-chat', 'paper', 'MÔI TRƯỜNG HỌC TẬP', 'Không gian học tập<br><em>hiện đại & xanh</em>', `<div class="infrastructure">${r.infrastructure.map(([value, label]) => `<article class="reveal"><strong>${value}</strong><h3>${label}</h3></article>`).join('')}</div>${reel('campus', 'Cơ sở vật chất và khuôn viên nhà trường', 'wide-reel')}${notes(['Thư viện mở, tủ sách lớp học và không gian xanh.', 'Nhà thi đấu, phòng học đạt chuẩn và thiết bị dạy học.', 'Chỉnh trang phòng học, xây dựng môi trường xanh – sạch – đẹp.'])}`)}
  ${section('phat-trien-doi-ngu', 'white', 'ĐỘI NGŨ & NGUỒN LỰC', 'Nâng cao năng lực.<br><em>Nuôi dưỡng sự tận tâm.</em>', `${split(notes(['Bồi dưỡng tin học, ngoại ngữ và năng lực nghiên cứu khoa học.', 'Nâng cao năng lực chủ nhiệm, tư vấn học đường và phụ trách CLB.', 'Rà soát, sắp xếp giáo viên; đánh giá theo chuẩn của Bộ GDĐT.', 'Quản trị dân chủ, kỷ cương; huy động nguồn lực phát triển giáo dục.']), reel('teachers', 'Đội ngũ giáo viên và nhân viên'))}${notes(['Xây dựng kho học liệu dùng chung, Google Education và E-Learning LMS.'])}`)}
  ${section('chi-tieu', 'forest', 'CHỈ TIÊU HỌC SINH · 2026–2027', 'Mục tiêu <em>rõ ràng</em>', `<div class="target-grid">${r.targets.map((item, i) => `<article class="target-item reveal" style="--delay:${i * 120}ms"><div class="target-ring" style="--target:${item.value}"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="ring-track" cx="60" cy="60" r="52"/><circle class="ring-fill" cx="60" cy="60" r="52" pathLength="100"/></svg><strong>${count(item)}</strong></div><h3>${item.label}</h3></article>`).join('')}</div>${notes([r.targetMore[0][1]])}`)}
  ${section('chi-tieu-thi-dua', 'white', 'CHỈ TIÊU ĐỘI NGŨ & TẬP THỂ', 'Cùng phấn đấu.<br><em>Cùng tiến bước.</em>', `${metrics(r.teacherTargets)}${notes([r.targetMore[2][1]])}${wall('teachers', 'Tập thể sư phạm nhà trường')}`)}
  ${section('dong-hanh', 'mint', 'NHÀ TRƯỜNG · GIA ĐÌNH · HỌC SINH', 'Cùng nhau <em>đồng hành</em>', `<div class="partnership-grid">${r.partnership.map(([title, text], i) => `<article class="reveal"><span>0${i + 1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div>${reel('students', 'Sự đồng hành của gia đình, thầy cô và học sinh', 'wide-reel')}`)}
  <section id="cam-on" class="closing-section" aria-labelledby="cam-on-title"><div class="closing-image">${image(photos.school[0], 'Cộng đồng học sinh THPT Phú Nhuận')}</div><div class="closing-shade"></div><div class="wrap closing-content"><p class="eyebrow reveal">TRƯỜNG THPT PHÚ NHUẬN</p><h2 id="cam-on-title" class="reveal">Xin cảm ơn<br><em>sự tin tưởng & đồng hành</em><br>của quý phụ huynh.</h2><p class="reveal">Cùng vun đắp một môi trường học tập<br>an toàn, hạnh phúc và phát triển.</p></div></section>`;
}
